## cacheSolve returns the inverse of a matrix 'x'
## 'x' is a special object generated by the function makeCacheMatrix
## the inverse is returned :
## either from the cached version inv if it exists - with a message "getting cached data"
## either from calculation and then store it in the cache inv
## 
## example of use :
## mymat1 <- rbind(c(3, -1/2, 1), c(-1/2, 3,1/3), c(1, 1/3,3))
## mymat2 <- rbind(c(3, -1/6, 1), c(-1/6, 3,1/4), c(1, 1/4,3))
## smat1 <- makeCacheMatrix(mymat1)
## cacheSolve(smat1)
## cacheSolve(smat1)
## smat2 <- makeCacheMatrix(mymat2)
## cacheSolve(smat2)
## cacheSolve(smat1)



## makeCacheMatrix generates a list of functions taking a matrix as argument
## inv is the cached matrix
## getmat()  return the matrix
## setinv() store the inversed matrix in "inverse" from the parent context (using <<- operator)
## getinv, return the inverse matrix
##
makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  
  getmat <- function() x
  setinv <- function(iv) inverse <<- iv
  getinv <- function () inverse
  list(getmat = getmat, setinv = setinv, getinv = getinv)
  
}


## cacheSolve returns the inverse of a special object matrix 'x'
## from cache if exists or freshly calculated by solve()
cacheSolve <- function(b, ...) {
  ## Return a matrix that is the inverse of 'b'
  ## 'b' is a special matrix generated by makeCacheMatrix()
  inverse <- b$getinv()
  if(!is.null(inverse)) {
    message("getting cached data")
    return(inverse)
  }
  data <- b$getmat()
  inverse <- solve(data)
  b$setinv(inverse)
  inverse
}